### ISSUE TITLE
Writing inline math directly

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#24]
It seems that the only possible way to write an inline math in the current version is to enter `$ $`, however, I believe many people would prefer typing the math content before the second `$` sign. Would you consider adding this feature? If not, why?

**Comment by 1943time** [comment]
It is to create an area that can be highlighted. If you think using the $ to create is very cumbersome, you can use `mod+option+k` to create inline formulas. Its shortcut keys are in paragraph ->formula, which requires version 0.12.9 or Mac store 1.5.7, Because in previous versions, there was an issue with not focusing when using shortcut keys. mac store needs to wait a little longer.

**Comment by chen-yingfa** [comment]
The hotkey is great, but I think it is desirable that the user can choose between the two options (to type out the Markdown syntax directly without highlighting, or to create a highlighted area using the hotkey or `$ $`).

**Comment by 1943time** [comment]
If you add `$\ int $` and convert it to an inline formula when entering the last $, is it what you want

**Comment by chen-yingfa** [comment]
Yes, would you consider this feature?

**Comment by 1943time** [comment]
I can add it to the next version, which may need to be manually turned on or off because some people may not need this feature.

**Comment by 1943time** [comment]
The function has been added and does not require configuration. I will close this issue first.
