### ISSUE TITLE
Task List line breaks bug

### ISSUE THREAD

**Issue by ww-wolt** [1943time/bluestone#31]
There is a little bug when formatting task lists. When I put line breaks between the items, they are somehow not saved. When I close and reopen the application the line breaks are reset. 

Line Breaks formatting  

![Bildschirmfoto 2024-01-13 um 10 03 56](https://github.com/1943time/bluestone/assets/55745851/24c2de72-77e8-4fb4-abe2-48dfa9792957)

No line breaks anymore when reopening the application  

<img width="381" alt="Bildschirmfoto 2024-01-13 um 10 04 30" src="https://github.com/1943time/bluestone/assets/55745851/c258514c-5bd7-4229-9819-58f3198c4848">

**Comment by 1943time** [comment]
This is because the current mainstream markdown parser behavior is such that no matter how many lines are left between two lists, they will be ignored during parsing. At present, it is recommended to use dividing lines or other elements to interrupt them.
<img width="813" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/88e2d4ee-2a52-4eeb-b4ed-e4eff7c4badc">
The same goes for vscode.

**Comment by ww-wolt** [comment]
what about just adding `<br/>` in that case? 
similar to the color formattings in Bluestone that are also done with HTML

**Comment by 1943time** [comment]
This approach can be considered, but some modifications and testing are required for the existing export and parsing.

**Comment by yu2chuan** [comment]
about \<br/>, can it be used in the table? Sometimes, users need to break line in the table.

**Comment by 1943time** [comment]
<img width="805" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/6eeb83da-6ceb-4ad1-b5f4-0d444bf93989">
Bluestone does not directly parse HTML content, but can wrap lines within the table using shortcut keys, What will be used in exporting source code is<br/>

**Comment by 1943time** [comment]
Hello, This issue has been resolved in the new version.
