### ISSUE TITLE
Scrollbar background is white in dark mode in MacOS

### ISSUE THREAD

**Issue by chen-yingfa** [1943time/bluestone#40]
In MacOS, when using dark mode, the background of the scrollbar is white, but I believe it should be the same as the document background. As shown below.

<img width="95" alt="image" src="https://github.com/1943time/bluestone/assets/54496664/3e698a94-5b7b-4507-827d-7decbec7aa6c">

**Comment by 1943time** [comment]
<img width="254" alt="image" src="https://github.com/1943time/bluestone/assets/115093678/ec5cce60-e7ff-4dc4-8900-9a4611f7ce05">
The default color of the browser's scrollbar is black, and it will only change color when you move the mouse into the scrollbar area. Generally, the color of the scrollbar will not be manually adjusted because once the scrollbar color is set, it will not automatically disappear, which is determined by the browser's characteristics.

**Comment by chen-yingfa** [comment]
I am thinking about the background. It should be transparent as shown in the picture you posted. However, in my system, the background is white (while the background of the application is dark gray, which makes the scrollbar stand out. Moreover, in my system, the scroll does not disappear automatically.

**Comment by 1943time** [comment]
Is the scrollbar of other software or browsers transparent in your system? Because the scroll bar has not been specially set, it should be consistent with the system scroll bar.

**Comment by chen-yingfa** [comment]
Strange, it is transparent other apps in my system (I checked at least Finder, Microsoft Edge, Obsidian, Mail, Terminal)

**Comment by 1943time** [comment]
This is a bit difficult to solve. My Mac computer cannot reproduce it. I don't know the reason behind this.

**Comment by leookun** [comment]
Same problem with macos monterey

https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme

<img width="400" alt="image" src="https://github.com/1943time/bluestone/assets/131544788/f3172db6-87aa-4ce3-8107-45ebfcd5fcf6">


this css above solves that, also bluestone-service 
```css
html.dark{
color-scheme: dark;
}
```

<img width="400" alt="image" src="https://github.com/1943time/bluestone/assets/131544788/531be2df-6e9d-40dd-8804-c75dd3e5de89">
