### ISSUE TITLE
Add Two Factor Authentication

### ISSUE THREAD

**Issue by TomosLeggett** [1943time/bluestone#80]
To enhance the security of this web application, I'd like to be able to add two factor authentication so that if someone was able to get a hold of my account password, they still wouldn't be able to log in without a 6 digit code generated by an authenticator app.

Better yet, allow people to set their own custom SSO server and bypass the login screen entirely for single-user experience.

**Comment by 1943time** [comment]
The web version is undergoing significant optimization, and the new version may consider adding email verification code login. Currently, if you enter the password incorrectly for 5 consecutive times, your account will be locked for 1 hour and you will not be able to log in. Regarding SSO, it is not currently supported because there are still many details to be fixed in the web version.

Thank you for your feedback.
